### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by IT-Berater** [x72y5e/radar#3]
Hi,

i update to python3 and install numpy-1.15.4-cp35-cp35m-linux_armv6l.whl on my headless Raspberry Pi (without X-Server) and install unicornhathd.

Thist is the error:

python3 ./tracker.py 52 9
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tracker.py", line 5, in <module>
    import numpy as np
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by IT-Berater** [comment]
Ok, i fix the error.

It works for 3 Airplane, and then Error ...FileNotFoundError

ello from the pygame community. https://www.pygame.org/contribute.html
enter coordinate (in format lat, long) for bottom-left of the map: (or press enter for default) 52.438837, 9.742816
enter coordinate (in format lat, long) for top-right of the map: (or press enter for default)
enter coordinates (in format lat, long) for any fixed point, or press enter to continue:
getting data...
From: LIRF Leonardo Da Vinci (Fiumicino), Rome, Italy
To: EGGW London Luton, United Kingdom
Type: Airbus A319 111
Operator: easyJet Europe
Altitude: 13975
Last Info: 0.01 seconds ago

From: EDDB Berlin-Sch�nefeld, Berlin, Germany
To: EGGD Bristol, United Kingdom
Type: Airbus A319 111
Operator: easyJet
Altitude: 29950
Last Info: 0.03 seconds ago

From: None
To: None
Type: Boeing 737NG 8AS/W
Operator: Ryanair
Altitude: 12125
Last Info: 0.04 seconds ago

From: EGLL London Heathrow, United Kingdom
To: HECA Cairo, Egypt
Type: Boeing 737NG 800/W
Operator: Egyptair
Altitude: 25
Last Info: 0.05 seconds ago

From: EGLL London Heathrow, United Kingdom
To: UUEE Sheremetyevo, Moscow, Russia
Type: Airbus A321 211
Operator: Aeroflot Russian Airlines
Altitude: 950
Last Info: 0.07 seconds ago

From: EGLL London Heathrow, United Kingdom
To: LTBA Atat�rk, Istanbul, Turkey
Type: Airbus A321 231SL
Operator: Turkish Airlines
Altitude: 3725
Last Info: 0.08 seconds ago

Traceback (most recent call last):
  File "./tracker.py", line 163, in <module>
    track(fixed, x_low, x_high, y_low, y_high, 18.)
  File "./tracker.py", line 129, in track
    plot(grid)
  File "./tracker.py", line 25, in plot
    u.show()
  File "/usr/local/lib/python3.5/dist-packages/unicornhathd/__init__.py", line 269, in show
    setup()
  File "/usr/local/lib/python3.5/dist-packages/unicornhathd/__init__.py", line 102, in setup
    _spi.open(0, 0)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by x72y5e** [comment]
To clarify, do you have a UnicornHatHD and have you installed the associated python module to manipulate it? Or are you just trying to use it without the UnicornHat display?

**Comment by IT-Berater** [comment]
I have no UnicornHat display and i installed only the UnicornHadHD modul, because it is necessary for the script :-(

**Comment by x72y5e** [comment]
You need the screen really. I am working on an emulator so that you can use pygame instead.
