### ISSUE TITLE
ImportError: No module named 'unicornhathd'

### ISSUE THREAD

**Issue by IT-Berater** [x72y5e/radar#6]
Hi,

i have Successfully uninstalled unicornhathd-0.0.4 then:

python3 ./tracker.py
Traceback (most recent call last):
  File "./tracker.py", line 12, in <module>
    import unicornhathd as u
ImportError: No module named 'unicornhathd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tracker.py", line 14, in <module>
    except ModuleNotFoundError:
**NameError: name 'ModuleNotFoundError' is not defined**

**Comment by x72y5e** [comment]
Are you sure you are using Python 3 and not 2? ModuleNotFoundError should be defined in 3, but it is not in 2. I have replaced the ModuleNotFoundError with ImportError anyway - this should work for you.

**Comment by IT-Berater** [comment]
~/radar $ python3 -V
**Python 3.5.3**

**Comment by IT-Berater** [comment]
Works fine. Thanks:

me:~/radar $ python3 ./tracker.py
No unicorn hat found. Printing to console only.
getting data...
52.185 -0.45799999999999996 19.0
From: None
To: None
Type: Cyclone Airsports Pegasus Quantum 15-912
Operator: Private
Altitude: 1550
Last Info: 0.01 seconds ago

From: None
To: None
Type: Vans RV-9 A
Operator: Private
Altitude: 1800
Last Info: 0.03 seconds ago

What are the right values for config.json?

{"bottom_left": [51.074, **-0.713**],
 "top_right":  [53.296, **-0.203**],
 "fixed_points": [[52.438, **-0.464**]],
 "range": 19.0}

What is the bold Value? And is the range in km or miles?
