### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xbc' in position 6

### ISSUE THREAD

**Issue by IT-Berater** [x72y5e/radar#7]
Hi,

i have this error:

~/radar $ python3 ./tracker.py
No unicorn hat found. Printing to console only.
getting data...
52.185 -0.45799999999999996 19.0
From: Traceback (most recent call last):
  File "./tracker.py", line 162, in <module>
    track(fixed, x_low, x_high, y_low, y_high, r)
  File "./tracker.py", line 124, in track
    display_to_console(current_ac)
  File "./tracker.py", line 68, in display_to_console
    print("From:", p.From)
  File "/usr/lib/python3.5/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xbc' in position 6: character maps to <undefined>

**Comment by x72y5e** [comment]
OK this needs some error handling. I will look into it unless you want to try a fix? I suspect it just needs a try-except block in the relevant function.
